export const EDITOR_COLORS = {
  background: '#fafafa',
  gutter: '#f0f0f0',
  gutterBorder: '#ddd',
  tabBar: '#ececec',
  tabActive: '#fafafa',
  statusBar: '#007acc',
  statusBarError: '#c62828',
  activeLine: '#e8f0fe',
  executingLine: '#e8f5e9',
  executingLineCode: '#f1f8e9',
  reviewingLine: '#fff8e1',
  reviewingLineCode: '#fffde7',
  errorLine: '#fde8e8',
  errorLineCode: '#fff5f5',
  errorAccent: '#e53935',
  text: '#24292e',
  gutterText: '#9ca3af',
  tabText: '#444',
  border: '#ccc',
} as const;
